"""Seed data: 21 sections of HireFast questions + default settings."""

# Section keys used throughout the app
SECTIONS = [
    {"key": "repetition", "num": 1, "name": "Sentence Repetition", "type": "voice", "timer": 30, "per_session": 3, "desc": "Listen to a sentence and repeat it accurately."},
    {"key": "reading", "num": 2, "name": "Reading Aloud", "type": "voice", "timer": 45, "per_session": 2, "desc": "Read a short passage aloud clearly and fluently."},
    {"key": "vocabulary", "num": 3, "name": "Vocabulary Fill-in", "type": "mcq", "timer": 20, "per_session": 3, "desc": "Choose the correct word to complete the sentence."},
    {"key": "comprehension", "num": 4, "name": "Comprehension Q&A", "type": "voice", "timer": 60, "per_session": 2, "desc": "Read a passage and answer the question verbally."},
    {"key": "typing", "num": 5, "name": "Typing Skills", "type": "typing", "timer": 90, "per_session": 2, "desc": "Type the reference paragraph as accurately as possible."},
    {"key": "story", "num": 6, "name": "Story Retelling", "type": "voice_story", "timer": 90, "per_session": 2, "desc": "Listen to a short story and retell it in your own words."},
    {"key": "jam", "num": 7, "name": "Just A Minute (JAM)", "type": "voice_jam", "timer": 60, "per_session": 1, "desc": "Speak continuously on a topic for one minute."},
    {"key": "conversation", "num": 8, "name": "Situational Conversations", "type": "ai_chat", "timer": 0, "per_session": 1, "desc": "Hold a real-time conversation with the AI for 3 turns."},
    {"key": "use_case", "num": 9, "name": "Use Case Questions", "type": "voice", "timer": 90, "per_session": 2, "desc": "Explain how you would handle a workplace scenario."},
    {"key": "sentence_building", "num": 10, "name": "Sentence Building", "type": "typing_build", "timer": 45, "per_session": 3, "desc": "Build correct sentences from given words or topics."},
    {"key": "picture", "num": 11, "name": "Picture Description", "type": "voice_image", "timer": 60, "per_session": 1, "desc": "Describe a workplace image in detail."},
    {"key": "opinion", "num": 12, "name": "Opinion Based", "type": "voice", "timer": 60, "per_session": 1, "desc": "Share your opinion with reasoning."},
    {"key": "role_play", "num": 13, "name": "Role Play (AI)", "type": "ai_chat", "timer": 0, "per_session": 1, "desc": "Take on a role in a simulated workplace conversation."},
    {"key": "pronunciation", "num": 14, "name": "Pronunciation Check", "type": "voice_words", "timer": 30, "per_session": 1, "desc": "Pronounce 5 challenging words clearly."},
    {"key": "interview", "num": 15, "name": "Interview Simulation (AI)", "type": "ai_interview", "timer": 0, "per_session": 1, "desc": "Answer 3 standard HR interview questions."},
    {"key": "email", "num": 16, "name": "Email Writing", "type": "typing_email", "timer": 120, "per_session": 1, "desc": "Compose a professional email."},
    {"key": "grammar", "num": 17, "name": "Grammar Correction", "type": "typing_correct", "timer": 30, "per_session": 3, "desc": "Rewrite each sentence with correct grammar."},
    {"key": "listening", "num": 18, "name": "Listening & Answering", "type": "voice_listen", "timer": 60, "per_session": 1, "desc": "Listen to an audio clip and answer two questions."},
    {"key": "dictation", "num": 19, "name": "Dictation", "type": "typing_dictation", "timer": 30, "per_session": 3, "desc": "Type exactly what you hear."},
    {"key": "word_assoc", "num": 20, "name": "Word Association", "type": "voice_assoc", "timer": 20, "per_session": 2, "desc": "Speak related words to a target word."},
    {"key": "paraphrasing", "num": 21, "name": "Paraphrasing", "type": "paraphrasing", "timer": 60, "per_session": 2, "desc": "Rewrite the sentence keeping its meaning."},
]

QUESTIONS_POOL = {
    "repetition": [
        {"prompt": "Listen and repeat the sentence.", "sentence": "The quarterly report was submitted before the deadline."},
        {"prompt": "Listen and repeat the sentence.", "sentence": "She coordinated the entire project with minimal supervision."},
        {"prompt": "Listen and repeat the sentence.", "sentence": "Our team successfully launched the new product in three markets."},
        {"prompt": "Listen and repeat the sentence.", "sentence": "The client requested a detailed breakdown of the project costs."},
        {"prompt": "Listen and repeat the sentence.", "sentence": "All employees are required to complete the training by Friday."},
    ],
    "reading": [
        {"prompt": "Read the passage aloud clearly.", "passage": "Customer satisfaction is central to our business strategy. We continuously gather feedback to improve our products and services, ensuring every client receives exceptional support."},
        {"prompt": "Read the passage aloud clearly.", "passage": "Effective communication in the workplace requires clarity, active listening, and empathy. Professionals who master these skills resolve conflicts and collaborate productively."},
        {"prompt": "Read the passage aloud clearly.", "passage": "Technology has transformed how organizations operate. From automating tasks to enabling real-time collaboration, digital tools are essential to maintaining a competitive edge."},
    ],
    "vocabulary": [
        {"sentence": "The new policy will _____ all employees.", "options": ["affect", "effect", "infect", "inspect"], "correctAnswer": "affect"},
        {"sentence": "She gave a very _____ presentation.", "options": ["compelling", "compiling", "complying", "comparing"], "correctAnswer": "compelling"},
        {"sentence": "The manager asked for a _____ summary.", "options": ["concise", "concrete", "concerned", "conscious"], "correctAnswer": "concise"},
        {"sentence": "He demonstrated excellent _____ skills.", "options": ["communication", "commutation", "commemoration", "compilation"], "correctAnswer": "communication"},
        {"sentence": "The team worked _____ to meet the deadline.", "options": ["collaboratively", "comparatively", "collectively", "conversely"], "correctAnswer": "collaboratively"},
        {"sentence": "Her _____ approach impressed the team.", "options": ["analytical", "anatomical", "analogical", "anarchical"], "correctAnswer": "analytical"},
    ],
    "comprehension": [
        {"passage": "TechFlow Inc. reported a 24% revenue increase, driven by cloud services. They plan to expand into three new international markets.", "question": "What was the main driver of TechFlow's revenue increase?"},
        {"passage": "Remote work changed team collaboration. Productivity increased but communication and cohesion challenges remain key concerns.", "question": "What are the key challenges managers face with remote work?"},
        {"passage": "Supply chain disruptions forced companies to shift from just-in-time to just-in-case inventory models, prioritizing resilience.", "question": "How have companies responded to supply chain disruptions?"},
    ],
    "typing": [
        {"prompt": "Type the paragraph below as accurately as possible.", "paragraph": "The meeting has been rescheduled to Thursday at 3:00 PM. Please make sure all team members are informed and the conference room is booked in advance."},
        {"prompt": "Type the paragraph below as accurately as possible.", "paragraph": "Effective communication is the foundation of a successful workplace. It ensures tasks are completed on time and team collaboration is strengthened."},
        {"prompt": "Type the paragraph below as accurately as possible.", "paragraph": "Please review the attached document and provide feedback by end of day Friday. Reach out to the project coordinator directly for assistance."},
    ],
    "story": [
        {"prompt": "Listen to the story, then retell it in your own words.", "storyText": "Riya joined a company as a marketing executive. She noticed no campaign tracking process and proposed a dashboard. Within two weeks efficiency improved by 30%."},
        {"prompt": "Listen to the story, then retell it in your own words.", "storyText": "A restaurant struggled with long wait times. The owner introduced online reservations and trained staff. Complaints dropped 50% and reviews doubled."},
        {"prompt": "Listen to the story, then retell it in your own words.", "storyText": "Arjun noticed a recurring bug affecting thousands of users. He worked overtime to fix it without waiting for approval, saving the company from a data breach."},
    ],
    "jam": [
        {"topic": "The importance of punctuality in the workplace"},
        {"topic": "How technology has changed the way we communicate"},
        {"topic": "The benefits of teamwork in achieving goals"},
        {"topic": "Why customer service is critical for business success"},
        {"topic": "The role of leadership in motivating a team"},
        {"topic": "How to handle work pressure and meet deadlines"},
        {"topic": "The impact of social media on professional life"},
        {"topic": "Why continuous learning is important in today's world"},
    ],
    "conversation": [
        {"title": "Applying for Leave", "context": "Employee requesting 3 days casual leave from manager.", "opening": "Before I approve, why do you need leave and how will you handle pending work?", "role": "manager"},
        {"title": "Hotel Booking", "context": "Guest calling to book a room for 2 nights.", "opening": "Thank you for calling Grand Stay Hotel. How may I assist you?", "role": "hotel receptionist"},
        {"title": "Restaurant Conversation", "context": "Customer ordering food and making a dietary request.", "opening": "Good evening! Would you like our menu or hear today's specials?", "role": "waiter"},
        {"title": "Deadline Extension", "context": "Employee requesting a 2-day extension due to technical issues.", "opening": "Your deliverable is due tomorrow. Is everything on track?", "role": "manager"},
        {"title": "Angry Client", "context": "Customer service agent handling a damaged order complaint.", "opening": "My order arrived completely damaged. I want a full refund right now!", "role": "angry customer"},
        {"title": "Delayed Project", "context": "Employee explaining a project milestone delay to manager.", "opening": "Can you walk me through what caused the delay in the timeline?", "role": "manager"},
    ],
    "use_case": [
        {"prompt": "A key team member goes on sick leave with a 3-day deadline. What do you do?"},
        {"prompt": "Your manager gives wrong product info in a client meeting. How do you handle it?"},
        {"prompt": "Client emails at 5:45 PM Friday needing a report by Monday. Team has left. What do you do?"},
        {"prompt": "A colleague takes credit for your work in front of the manager. How do you handle this professionally?"},
        {"prompt": "You must lead a team meeting with only 10 minutes notice on quarterly performance. How do you prepare?"},
        {"prompt": "An unhappy client threatens to cancel their contract and you're the only one available. What do you do?"},
    ],
    "sentence_building": [
        {"buildType": "jumble", "wordsList": ["submitted", "report", "before", "was", "the", "deadline"], "correctAnswer": "The report was submitted before the deadline."},
        {"buildType": "jumble", "wordsList": ["team", "the", "project", "successfully", "completed"], "correctAnswer": "The team successfully completed the project."},
        {"buildType": "jumble", "wordsList": ["client", "satisfaction", "our", "priority", "is", "top"], "correctAnswer": "Client satisfaction is our top priority."},
        {"buildType": "jumble", "wordsList": ["meeting", "the", "rescheduled", "been", "has", "Thursday", "to"], "correctAnswer": "The meeting has been rescheduled to Thursday."},
        {"buildType": "topic", "topic": "TEAMWORK"},
        {"buildType": "topic", "topic": "DEADLINE"},
        {"buildType": "topic", "topic": "CUSTOMER SERVICE"},
        {"buildType": "topic", "topic": "LEADERSHIP"},
        {"buildType": "topic", "topic": "COMMUNICATION"},
    ],
    "picture": [
        {"prompt": "Describe what you see in this image.", "imageUrl": "https://images.unsplash.com/photo-1497366216548-37526070297c?w=900&q=80"},
        {"prompt": "Describe what you see in this image.", "imageUrl": "https://images.unsplash.com/photo-1552664730-d307ca884978?w=900&q=80"},
        {"prompt": "Describe what you see in this image.", "imageUrl": "https://images.unsplash.com/photo-1573497019236-17f8177b81e8?w=900&q=80"},
    ],
    "opinion": [
        {"prompt": "Is work from home more productive than office? Why?"},
        {"prompt": "Should companies prioritize employee happiness over productivity?"},
        {"prompt": "Is teamwork always better than working individually?"},
        {"prompt": "Will AI replace human jobs in the next 10 years?"},
        {"prompt": "Should freshers be given leadership roles early in their career?"},
    ],
    "role_play": [
        {"title": "Sales Pitch", "context": "Sales executive convincing a client to buy enterprise software.", "opening": "I already use a competitor. Why should I switch to yours?", "role": "skeptical client"},
        {"title": "Job Interview", "context": "Candidate interviewing for a Team Lead position.", "opening": "Welcome! Tell me about yourself and why you applied.", "role": "interviewer"},
        {"title": "Performance Review", "context": "Employee in an annual performance review.", "opening": "Let's discuss your performance this year. How do you feel you've done?", "role": "manager"},
    ],
    "pronunciation": [
        {"wordsList": ["entrepreneur", "collaborate", "efficiency", "articulate", "professional"]},
        {"wordsList": ["communication", "initiative", "perseverance", "sophisticated", "presentation"]},
        {"wordsList": ["organizational", "circumstances", "accomplishment", "particularly", "responsibilities"]},
    ],
    "interview": [
        {"questions": [
            "Tell me about yourself and your professional background.",
            "What are your key strengths and how have they helped you?",
            "Where do you see yourself in the next 5 years?",
        ]},
    ],
    "email": [
        {"prompt": "Write a professional email apologizing to a client for a 2-day project delay. Assure delivery by tomorrow."},
        {"prompt": "Write an email to your team about a mandatory training session to be completed by end of this month."},
        {"prompt": "Write a follow-up email to a client after a product demo. Thank them and summarize key points discussed."},
    ],
    "grammar": [
        {"sentence": "She don't knows how to handles the situation.", "correctAnswer": "She doesn't know how to handle the situation."},
        {"sentence": "The team have completed their work before the deadline yesterday.", "correctAnswer": "The team completed their work before the deadline yesterday."},
        {"sentence": "He goed to the meeting and speaked very good.", "correctAnswer": "He went to the meeting and spoke very well."},
        {"sentence": "Neither the manager nor the employees was aware of the change.", "correctAnswer": "Neither the manager nor the employees were aware of the change."},
        {"sentence": "If I was you, I would have accepted the offer immediately.", "correctAnswer": "If I were you, I would accept the offer immediately."},
    ],
    "listening": [
        {"audioText": "All staff: annual team building event on the 15th. All departments must participate. Confirm attendance with team lead by end of week. Lunch provided.", "questions": ["When is the team building event?", "What must employees do by end of this week?"]},
        {"audioText": "Quick update: client moved final delivery from 20th to 18th. Testing must complete by 16th. Flag blockers to leads by today afternoon.", "questions": ["What change did the client request?", "By when must testing be completed?"]},
    ],
    "dictation": [
        {"audioText": "Please send the updated report to all stakeholders by 5 PM today."},
        {"audioText": "The client meeting has been confirmed for next Monday at 10 AM."},
        {"audioText": "All team members must submit their weekly updates every Friday."},
        {"audioText": "The new office policy requires employees to log their work hours daily."},
        {"audioText": "Kindly review the attached proposal and share your feedback at the earliest."},
    ],
    "word_assoc": [
        {"topic": "OFFICE"},
        {"topic": "COMMUNICATION"},
        {"topic": "LEADERSHIP"},
        {"topic": "CUSTOMER"},
    ],
    "paraphrasing": [
        {"sentence": "The manager informed the team that the project deadline has been moved to the following week due to unforeseen technical challenges."},
        {"sentence": "Customer feedback is essential for improving our products and ensuring clients remain satisfied with our services."},
        {"sentence": "Effective leadership involves directing the team while also listening to their concerns and motivating them to achieve their best."},
        {"sentence": "The company implemented a new work from home policy allowing employees to work remotely on Wednesdays and Fridays."},
    ],
}
